export var boardPositions: object[][] = [
  [
    { 'value': 'a8', 'color': 'black' },
    { 'value': 'b8', 'color': 'white' },
    { 'value': 'c8', 'color': 'black' },
    { 'value': 'd8', 'color': 'white' },
    { 'value': 'e8', 'color': 'black' },
    { 'value': 'f8', 'color': 'white' },
    { 'value': 'g8', 'color': 'black' },
    { 'value': 'h8', 'color': 'white' },
  ],
  [
    { 'value': 'a7', 'color': 'white' },
    { 'value': 'b7', 'color': 'black' },
    { 'value': 'c7', 'color': 'white' },
    { 'value': 'd7', 'color': 'black' },
    { 'value': 'e7', 'color': 'white' },
    { 'value': 'f7', 'color': 'black' },
    { 'value': 'g7', 'color': 'white' },
    { 'value': 'h7', 'color': 'black' },
  ],
  [
    { 'value': 'a6', 'color': 'black' },
    { 'value': 'b6', 'color': 'white' },
    { 'value': 'c6', 'color': 'black' },
    { 'value': 'd6', 'color': 'white' },
    { 'value': 'e6', 'color': 'black' },
    { 'value': 'f6', 'color': 'white' },
    { 'value': 'g6', 'color': 'black' },
    { 'value': 'h6', 'color': 'white' },
  ],
  [
    { 'value': 'a5', 'color': 'white' },
    { 'value': 'b5', 'color': 'black' },
    { 'value': 'c5', 'color': 'white' },
    { 'value': 'd5', 'color': 'black' },
    { 'value': 'e5', 'color': 'white' },
    { 'value': 'f5', 'color': 'black' },
    { 'value': 'g5', 'color': 'white' },
    { 'value': 'h5', 'color': 'black' },
  ],
  [
    { 'value': 'a4', 'color': 'black' },
    { 'value': 'b4', 'color': 'white' },
    { 'value': 'c4', 'color': 'black' },
    { 'value': 'd4', 'color': 'white' },
    { 'value': 'e4', 'color': 'black' },
    { 'value': 'f4', 'color': 'white' },
    { 'value': 'g4', 'color': 'black' },
    { 'value': 'h4', 'color': 'white' },
  ],
  [
    { 'value': 'a3', 'color': 'white' },
    { 'value': 'b3', 'color': 'black' },
    { 'value': 'c3', 'color': 'white' },
    { 'value': 'd3', 'color': 'black' },
    { 'value': 'e3', 'color': 'white' },
    { 'value': 'f3', 'color': 'black' },
    { 'value': 'g3', 'color': 'white' },
    { 'value': 'h3', 'color': 'black' },
  ],
  [
    { 'value': 'a2', 'color': 'black' },
    { 'value': 'b2', 'color': 'white' },
    { 'value': 'c2', 'color': 'black' },
    { 'value': 'd2', 'color': 'white' },
    { 'value': 'e2', 'color': 'black' },
    { 'value': 'f2', 'color': 'white' },
    { 'value': 'g2', 'color': 'black' },
    { 'value': 'h2', 'color': 'white' },
  ],
  [
    { 'value': 'a1', 'color': 'white' },
    { 'value': 'b1', 'color': 'black' },
    { 'value': 'c1', 'color': 'white' },
    { 'value': 'd1', 'color': 'black' },
    { 'value': 'e1', 'color': 'white' },
    { 'value': 'f1', 'color': 'black' },
    { 'value': 'g1', 'color': 'white' },
    { 'value': 'h1', 'color': 'black' },
  ],
];

